#!/usr/bin/env node
const command = process.argv[2]
const args = process.argv.slice(3)

switch (command) {
  // case 'ls':
  // case 'list':
  default:
    const [file, ...rest] = args;
    createFile(file, rest)
}
